'use strict';
const P=window.ExaPlanning;
const planFields={'cpu-buffer':'cpuBuffer','memory-buffer':'memoryBuffer','storage-buffer':'storageBuffer','storage-capacity':'storageCapacity','storage-allocated':'storageAllocated','adb-ecpu':'adbECPU','session-rate':'sessionsPerECPU','session-demand':'sessionDemand'};
function renderPlanning(){const p=P.config(site());for(const [id,key] of Object.entries(planFields))$(id).value=p[key]===null?'':p[key];$('session-mode').value=p.sessionMode;$('clear-baseline').disabled=!site().baseline;}
function clearPlanning(){for(const id of ['resource-budgets','baseline-results','session-results'])$(id).innerHTML='<p class="hint">Complete valid inputs to calculate.</p>';}
function planningResults(s,r){
 try{const rows=P.resources(s,r),value=x=>x===null?'Not checked':fmt(x);$('resource-budgets').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Resource</th><th>Capacity</th><th>Allocated</th><th>Free</th><th>Buffer</th><th>Free after buffer</th><th>Check</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.name} (${x.unit})</td><td>${fmt(x.capacity)}</td><td>${fmt(x.allocated)}</td><td>${fmt(x.free)}</td><td>${x.percent}% · ${fmt(x.buffer)}</td><td class="${x.after<0?'negative':''}">${fmt(x.after)}</td><td>${x.status}</td></tr>`).join('')}</tbody></table></div>${rows.flatMap(x=>x.nodes.filter(n=>n.status!=='Within buffer').map(n=>`<p class="hint">DB ${n.id} · ${x.name}: ${n.status.toLowerCase()} (${fmt(n.after)} ${x.unit} after buffer).</p>`)).join('')}<p class="hint">${s.checkCompute?'CPU and memory checked on every DB server. Memory uses the published formula, not measured usage.':'Enable CPU / memory checks above to include those resources.'} Exadata storage requires both console capacity and total allocation inputs below.</p>`;
 const changes=P.compare(s,r);$('baseline-results').innerHTML=changes.length?`<div class="table-wrap"><table><thead><tr><th>Resource</th><th>Baseline</th><th>Proposed</th><th>Change (+ added / − released)</th></tr></thead><tbody>${changes.map(x=>`<tr><td>${x.name} (${x.unit})</td><td>${value(x.before)}</td><td>${value(x.after)}</td><td>${x.delta===null?'Not checked':(x.delta>0?'+':'')+fmt(x.delta)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="hint">Capture the current design, then edit its ECPUs, memory ratio, slots or AVMC count. The baseline stays fixed until replaced or cleared.</p>';
 const e=P.sessions(s);$('session-results').innerHTML=e?`<div class="issues"><strong>${fmt(e.estimated)} estimated sessions</strong> for this ADB, using ${fmt(e.rate)} sessions/ECPU.${e.demand===null?'':` Demand: ${fmt(e.demand)}; remaining: ${fmt(e.remaining)}. Arithmetic CPU requirement: ${fmt(e.requiredECPU)} ECPUs (subject to service increments and limits).`}<br>Assumption only. Validate the actual database session/process limits and connection configuration. This does not predict concurrent SQL throughput or availability during failover.</div>`:'<p class="hint">Enter the base ECPUs allocated to one ADB to estimate its sessions. Do not enter the AVMC pool or multiply by DB-server count.</p>';
 }catch(e){clearPlanning();message(e.message);}
}
function initPlanning(){
 for(const [id,key] of Object.entries(planFields))$(id).addEventListener('input',()=>safeUpdate(()=>{const p=site().planning={...P.config(site())};const blank=$(id).value==='';p[key]=blank&&['storageCapacity','storageAllocated','adbECPU','sessionDemand'].includes(key)?null:blank?NaN:Number($(id).value);if(key==='sessionsPerECPU'){p.sessionMode='custom';$('session-mode').value='custom';}P.validate(site());}));
 $('session-mode').onchange=()=>safeUpdate(()=>{const p=site().planning={...P.config(site())};p.sessionMode=$('session-mode').value;if(p.sessionMode!=='custom')p.sessionsPerECPU=p.sessionMode==='shared'?325:75;},true);
 $('capture-baseline').onclick=()=>safeUpdate(()=>{site().baseline=P.capture(site(),M.calculate(site()));},true);
 $('clear-baseline').onclick=()=>safeUpdate(()=>{delete site().baseline;},true);
}
