'use strict';
const P=window.ExaPlanning;
const planFields={'cpu-buffer':'cpuBuffer','memory-buffer':'memoryBuffer','storage-buffer':'storageBuffer','storage-capacity':'storageCapacity','storage-allocated':'storageAllocated','adb-ecpu':'adbECPU','session-rate':'sessionsPerECPU','session-demand':'sessionDemand'};
function renderPlanning(){const p=P.config(site());for(const [id,key] of Object.entries(planFields))$(id).value=p[key]===null?'':p[key];$('session-mode').value=p.sessionMode;$('clear-baseline').disabled=!site().baseline;}
function clearPlanning(){for(const id of ['resource-budgets','baseline-results','session-results'])$(id).innerHTML='<p class="hint">Complete valid inputs to calculate.</p>';}
function planningResults(s,r){
 try{const rows=P.resources(s,r),value=x=>x===null?'Not checked':fmt(x);$('resource-budgets').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Resource</th><th>Capacity</th><th>Allocated</th><th>Free</th><th>Buffer target</th><th>Above / below target</th><th>Check</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${resourceLabel(x.name)} (${x.unit})</td><td>${fmt(x.capacity)}</td><td>${fmt(x.allocated)}</td><td>${fmt(x.free)}</td><td>${x.percent}% · ${fmt(x.buffer)}</td><td class="${x.free<0?'negative':x.after<0?'buffer-warning':''}">${fmt(x.after)}</td><td>${reserveLabel(x.status)}</td></tr>`).join('')}</tbody></table></div>${rows.flatMap(x=>x.nodes.filter(n=>n.status!=='Within buffer').map(n=>`<p class="hint">DB ${n.id} · ${x.name}: ${reserveLabel(n.status).toLowerCase()} (${fmt(n.free)} ${x.unit} free; target ${fmt(n.buffer)} ${x.unit}).</p>`)).join('')}<p class="hint">${s.checkCompute?'Each DB server is checked separately. Memory is calculated from its allocation, not live workload usage.':'Turn on CPU / memory checks to include them.'} Enter both shared-storage values below to check them.</p>`;
 const changes=P.compare(s,r);$('baseline-results').innerHTML=changes.length?`<div class="table-wrap"><table><thead><tr><th>Resource</th><th>Before (recorded)</th><th>After (editing now)</th><th>Change (+ added / − released)</th></tr></thead><tbody>${changes.map(x=>`<tr><td>${resourceLabel(x.name)} (${x.unit})</td><td>${value(x.before)}</td><td>${value(x.after)}</td><td>${x.delta===null?'Not checked':(x.delta>0?'+':'')+fmt(x.delta)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="hint">No “Before” values recorded. Capacity totals still work. Use “Record Before values” above only if you want to compare changes.</p>';
 const e=P.sessions(s);$('session-results').innerHTML=e?`<div class="issues"><strong>${fmt(e.estimated)} estimated sessions</strong> for this ADB, using ${fmt(e.rate)} sessions/ECPU.${e.demand===null?'':` Demand: ${fmt(e.demand)}; remaining: ${fmt(e.remaining)}. ECPUs needed using this ratio: ${fmt(e.requiredECPU)} ECPUs (subject to service increments and limits).`}<br>Estimate only. Check the database session limits and connection settings. More sessions do not guarantee faster SQL or uninterrupted failover.</div>`:'<p class="hint">Enter the ECPUs assigned to one ADB. Use the database allocation, not the whole AVMC or the DB-server count.</p>';
 }catch(e){clearPlanning();message(e.message);}
}
function initPlanning(){
 for(const [id,key] of Object.entries(planFields))$(id).addEventListener('input',()=>safeUpdate(()=>{const p=site().planning={...P.config(site())};const blank=$(id).value==='';p[key]=blank&&['storageCapacity','storageAllocated','adbECPU','sessionDemand'].includes(key)?null:blank?NaN:Number($(id).value);if(key==='sessionsPerECPU'){p.sessionMode='custom';$('session-mode').value='custom';}P.validate(site());}));
 $('session-mode').onchange=()=>safeUpdate(()=>{const p=site().planning={...P.config(site())};p.sessionMode=$('session-mode').value;if(p.sessionMode!=='custom')p.sessionsPerECPU=p.sessionMode==='shared'?325:75;},true);
 $('capture-baseline').onclick=()=>safeUpdate(()=>{site().baseline=P.capture(site(),M.calculate(site()));},true);
 $('clear-baseline').onclick=()=>safeUpdate(()=>{delete site().baseline;},true);
}
